import type { NextPage } from "next";
import Head from "next/head";
import styles from "./styles.module.scss";
import { Button, TextInput, Text, Title } from "@mantine/core";

import { BiUser, BiKey } from "react-icons/bi";
import { HiMenuAlt3 } from "react-icons/hi";

const Login: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.main}>
          <div className={styles.formSection}>
            <div></div>
            <div className={styles.form}>
              <TextInput
                icon={<BiUser color="black" />}
                placeholder="Your login or e-mail"
              />
              <TextInput
                icon={<BiKey color="black" />}
                placeholder="Password"
              />
              <div className={styles.buttons}>
                <div className={styles.miniButtons}>
                  <Button variant="subtle" compact>
                    <Text color="dimmed" size="xs">
                      Register
                    </Text>
                  </Button>

                  <Button variant="subtle" compact>
                    <Text color="dimmed" size="xs">
                      Forgot Password?
                    </Text>
                  </Button>
                </div>
                <Button color="orange" radius="sm">
                  Sign In
                </Button>
              </div>
            </div>

            <div className={styles.formOthers}>
              <Button variant="subtle" compact>
                <Text color="dimmed" size="xs" weight="400">
                  Login with
                </Text>
              </Button>
              <div>
                <Button variant="subtle" compact>
                  <Text color="orange" size="xs">
                    facebook
                  </Text>
                </Button>
                <Button variant="subtle" compact>
                  <Text color="orange" size="xs">
                    twitter
                  </Text>
                </Button>
                <Button variant="subtle" compact>
                  <Text color="orange" size="xs">
                    google
                  </Text>
                </Button>
              </div>
            </div>
          </div>
          <div className={styles.view}>
            <img src="/images/background2.jpg" className={styles.image} />
            <div
              className={styles.menuWrapper}
              onClick={() => {
                console.log("clicked");
              }}
            >
              <HiMenuAlt3 color="white" className={styles.menu} />
            </div>
            <div className={styles.viewContainer}>
              <div className={styles.lines}>
                <div className={styles.line}></div>
                <div className={styles.lineDisabled}></div>
              </div>
              <div className={styles.heading}>
                <Text color="white" weight="400">
                  Start collecting your
                </Text>
                <Title className={styles.title}>Reading</Title>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Login;
