import type { NextPage } from "next";
import Head from "next/head";


const Login: NextPage = () => {
    return (
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div >
          <p>Login page</p>
        </div>
      </div>
    );
  };
  
  export default Login;
  