import type { NextPage } from 'next';
import Head from 'next/head';
import styles from './styles.module.scss';
import { Button, TextInput, Text, Title, LoadingOverlay } from '@mantine/core';
import { useForm } from '@mantine/hooks';
import { BiUser, BiKey } from 'react-icons/bi';
import { HiMenuAlt3 } from 'react-icons/hi';
import { login } from "../../utils/api";
import { useDispatch } from "react-redux";
import {setUser} from "../../redux/user";
import Router from 'next/router'
import {useState} from "react";

const Login: NextPage = () => {
	const dispatch = useDispatch()
	const [visible, setVisible] = useState(false);

	const form = useForm({
		initialValues: {
			login: '',
			password: '',
		},

	});

	const submitForm = async (username: string, password: string) => {
		setVisible(true)
		const userKey = await login(username, password)
		if(userKey.length > 0) {
			dispatch(setUser({userKey: userKey, username: username}))
			Router.push("/")
			setVisible(false)
		}else {
			console.log("Please register")
		}
	}

	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<LoadingOverlay visible={visible} loaderProps={{ size: 'sm', color: 'green', variant: 'bars' }}/>
				<div className={styles.main}>
					<div className={styles.formSection}>

						<div></div>

						<form className={styles.form} onSubmit={form.onSubmit((values) => submitForm(values.login, values.password))}>

							<TextInput
								icon={<BiUser color="black" />}
								placeholder="Your login or e-mail"
								{...form.getInputProps('login')}
							/>
							<TextInput
								icon={<BiKey color="black" />}
								placeholder="Password"
								{...form.getInputProps('password')}
							/>

						<div className={styles.buttons}>

							<div className={styles.miniButtons}>
								<Button
									variant="subtle"
									color="green"
									compact
								>
									<Text color="dimmed" size="xs">
										Register
									</Text>
								</Button>

								<Button
									variant="subtle"
									color="green"
									compact
								>
									<Text color="dimmed" size="xs">
										Forgot Password?
									</Text>
								</Button>
							</div>
							<Button color="green" radius="sm" type={"submit"}>
								Sign In
							</Button>
						</div>
						</form>

						<div className={styles.formOthers}>
							<Button variant="subtle" compact >
								<Text color="dimmed" size="xs" weight="400">
									Login with
								</Text>
							</Button>
							<div>
								<Button variant="subtle" color="green" compact>
									<Text color="green" size="xs">
										facebook
									</Text>
								</Button>
								<Button variant="subtle" color="green" compact>
									<Text color="green" size="xs">
										twitter
									</Text>
								</Button>
								<Button variant="subtle" color="green" compact>
									<Text color="green" size="xs">
										google
									</Text>
								</Button>
							</div>
						</div>
					</div>
					<div className={styles.view}>
						<img
							src="/images/background2.jpg"
							className={styles.image}
						/>
						<div
							className={styles.menuWrapper}
							onClick={() => {
								console.log('clicked');
							}}
						>
							<HiMenuAlt3 color="white" className={styles.menu} />
						</div>
						<div className={styles.viewContainer}>
							<div className={styles.lines}>
								<div className={styles.line}></div>
								<div className={styles.lineDisabled}></div>
							</div>
							<div className={styles.heading}>
								<Text color="white" weight="400">
									Start collecting your
								</Text>
								<Title className={styles.title}>Reading</Title>
							</div>
						</div>
					</div>
				</div>
			</main>
		</div>
	);
};

export default Login;
