import {useRouter} from 'next/router'
import {useSelector} from "react-redux";
import {useEffect} from "react";
import {Container, Box, Grid, Header, Text, Group, Button, ActionIcon, Tabs} from "@mantine/core";
import {BiArrowBack, BiMoney} from "react-icons/all";
import Head from "next/head";
import Books from "../../components/Books";

const User = () => {
    const router = useRouter()
    const state: any = useSelector<any>((state) => state.user)
    const {user} = router.query

    useEffect(() => {
        if (state.userKey.length === 0) {
            router.push("/login")
        }
    }, [])

    return (
        <>
            <Head>
                <title>{user} profile</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Container style={{
                display: "flex",
                alignItems: 'center',
                justifyContent: 'space-between',
                padding: "12px",
            }}>
                <Button
                    variant="light"
                    leftIcon={<BiArrowBack/>}
                    onClick={() => router.push("/")}
                >
                    back
                </Button>
                <Text> {user} </Text>
                <Button
                    variant="light"
                    rightIcon={<BiMoney/>}
                    onClick={() => router.push("/")}
                    disabled
                >
                    Tip
                </Button>
            </Container>
            <Container size = {1600} style={{marginTop: "100px"}}>

                <Tabs>
                    <Tabs.Tab label="Books">
                        <Books username={user!.toString()}/>
                    </Tabs.Tab>
                    <Tabs.Tab label="Wishlist">Messages tab content</Tabs.Tab>
                </Tabs>
            </Container>
        </>
    )
}

export default User