import type { NextPage } from 'next';
import Head from 'next/head';
import {
	AppShell,
	Navbar,
	Header,
	Title,
	Text,
	ThemeIcon,
	Button,
	Grid,
	Center,
} from '@mantine/core';
import { BiBook, BiBookAdd, BiUser, BiTime } from 'react-icons/bi';

import styles from '../styles/Home.module.scss';
import { useState } from 'react';

import Book from '../components/Book';
import { BookInterface, BookStatus } from '../types/interfaces';
import Books from '../components/Books';
import Profile from '../components/Profile';

enum Option {
	books,
	addBook,
	profile,
}

const Home: NextPage = () => {
	const [menuOption, setMenuOption] = useState<Option>(Option.profile);
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className={styles.main}>
				<AppShell
					padding="md"
					navbar={
						<Navbar
							width={{ base: 250 }}
							height={'90vh'}
							padding="sm"
						>
							<Button
								variant={
									menuOption == Option.books
										? 'light'
										: 'subtle'
								}
								color="gray"
								className={styles.menuOption}
								onClick={() => {
									setMenuOption(Option.books);
								}}
							>
								<ThemeIcon
									className={styles.icon}
									variant="light"
								>
									<BiBook size="20px" />
								</ThemeIcon>

								<Text size="sm" weight={'400'} color="black">
									Books
								</Text>
							</Button>
							<Button
								variant={
									menuOption == Option.addBook
										? 'light'
										: 'subtle'
								}
								color="gray"
								className={styles.menuOption}
								onClick={() => {
									setMenuOption(Option.addBook);
								}}
							>
								<ThemeIcon
									className={styles.icon}
									variant="light"
									color="green"
								>
									<BiBookAdd size="20px" />
								</ThemeIcon>

								<Text size="sm" weight={'400'} color="black">
									Add Book
								</Text>
							</Button>
							<Button
								variant={
									menuOption == Option.profile
										? 'light'
										: 'subtle'
								}
								color="gray"
								className={styles.menuOption}
								onClick={() => {
									setMenuOption(Option.profile);
								}}
							>
								<ThemeIcon
									className={styles.icon}
									variant="light"
									color="grape"
								>
									<BiUser size="20px" />
								</ThemeIcon>

								<Text size="sm" weight={'400'} color="black">
									Your Profile
								</Text>
							</Button>
						</Navbar>
					}
					header={
						<Header height={'7vh'} padding="xs">
							<Center inline>
								<Title order={2}>book.io</Title>
							</Center>
						</Header>
					}
				>
					{menuOption === Option.books && <Books />}
					{menuOption === Option.addBook && <div>Add Book page </div>}
					{menuOption === Option.profile && <Profile />}
				</AppShell>
			</div>
		</div>
	);
};

export default Home;
